import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8787/api';
async function request(path, options = {}, token) { const response = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || 'Request failed.'); return body; }
function App() {
 const [token,setToken]=useState(localStorage.getItem('flins_token')||''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [mode,setMode]=useState('login'); const [command,setCommand]=useState(''); const [tasks,setTasks]=useState([]); const [status,setStatus]=useState('Ready'); const [notice,setNotice]=useState('Sign in to begin.'); const [listening,setListening]=useState(false); const recognition=useRef(null);
 const speak=(text)=>{ if('speechSynthesis' in window){ speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text)); } };
 const loadTasks=async()=>{ if(!token)return; try{const data=await request('/tasks',{},token);setTasks(data.tasks);}catch(e){setNotice(e.message);if(/session/i.test(e.message))logout();} };
 useEffect(()=>{loadTasks();},[token]);
 const auth=async(e)=>{e.preventDefault();setStatus('Authenticating');try{const data=await request('/auth/'+(mode==='login'?'login':'register'),{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('flins_token',data.token);setToken(data.token);setNotice(`Signed in as ${data.user.email}.`);setPassword('');}catch(err){setNotice(err.message);}finally{setStatus('Ready');}};
 const logout=()=>{localStorage.removeItem('flins_token');setToken('');setTasks([]);setNotice('Signed out.');};
 const run=async(text=command)=>{ if(!text.trim())return; setStatus('Processing');setNotice(`Working on “${text}”…`);try{const data=await request('/tasks',{method:'POST',body:JSON.stringify({command:text})},token);setTasks(old=>[data.task,...old]);setNotice(data.task.response);speak(data.task.response);setCommand('');}catch(err){setNotice(err.message);}finally{setStatus('Ready');}};
 const voice=()=>{const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){setNotice('Voice recognition is unavailable in this browser. Type your request instead.');return;}if(listening){recognition.current?.stop();return;}const r=new Speech();recognition.current=r;r.lang=navigator.language||'en-US';r.interimResults=true;r.onstart=()=>{setListening(true);setStatus('Listening');};r.onresult=(e)=>{const text=[...e.results].map(x=>x[0].transcript).join('');setCommand(text);if(e.results[e.results.length-1].isFinal)run(text);};r.onerror=(e)=>setNotice(e.error==='not-allowed'?'Microphone permission was denied.':'I could not understand that. Try again or type a command.');r.onend=()=>{setListening(false);setStatus('Ready');};r.start();};
 if(!token)return <main className="auth"><section><div className="brand"><i/>flins</div><p className="eyebrow">Secure command layer</p><h1>Make the request.<br/><em>Keep control.</em></h1><p className="sub">A functional voice assistant interface with authenticated task execution and an auditable history.</p><form onSubmit={auth}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" minLength="12" required value={password} onChange={e=>setPassword(e.target.value)} /></label><button>{mode==='login'?'Sign in':'Create account'}</button><button type="button" className="quiet" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already have an account? Sign in'}</button></form><p className="notice">{notice}</p></section></main>;
 return <main className="app"><header><div className="brand"><i/>flins</div><div><span className="statusDot"/> {status}<button className="logout" onClick={logout}>Sign out</button></div></header><section className="hero"><p className="eyebrow">Authenticated assistant</p><h1>Say less.<br/><em>Do more.</em></h1><p className="sub">Task requests are sent to the Flins API, validated, executed by the service router, and saved to your private history.</p><div className="commandBox"><button className={'mic '+(listening?'live':'')} onClick={voice} aria-label="Speak a command">⌁</button><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="Play a focus playlist, search YouTube, or read email…"/><button className="run" onClick={()=>run()}>Run</button></div><p className="notice">{notice}</p></section><section className="history"><div><p className="eyebrow">Task history</p><h2>What Flins did</h2></div><button className="refresh" onClick={loadTasks}>Refresh</button>{tasks.length===0?<p className="empty">No tasks yet. Start with a command above.</p>:<div className="tasks">{tasks.map(t=><article key={t.id}><div><b>{t.intent}</b><time>{new Date(t.createdAt).toLocaleString()}</time></div><p className="command">“{t.command}”</p><p>{t.response}</p><span className={'tag '+t.status}>{t.status.replace('_',' ')}</span></article>)}</div>}</section></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
